module.exports = {
  "stories": [
    "../src/**/*.stories.mdx",
    "../src/**/*.stories.@(js|jsx|ts|tsx)"
  ],
  "addons": [
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "@storybook/addon-interactions",
    "@storybook/addon-a11y"
  ],
  "framework": "@storybook/react",
  "core": {
    "builder": "@storybook/builder-vite"
  },
  "features": {
    "storyStoreV7": true,
    "interactionsDebugger": true,
  },
  "staticDirs": [ // where SB should look for static files
    "../public" // where the service worker for the MSW was generated
  ],
  viteFinal: (config, { configType }) => {
    // ensures that SB doesn't get lost in the URL generated by gh pages
    if (configType === 'PRODUCTION') {
      config.base = '/design-system-ignitelab/';
    }

    return config;
  }
}